server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personal-diary?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
